# Generated by Django 4.2.14 on 2024-07-19 09:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Obituary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('date_of_death', models.DateField()),
                ('content', models.TextField(default='Content not provided')),
                ('author', models.CharField(default='Anonymous', max_length=100)),
                ('submission_date', models.DateField(default=django.utils.timezone.now)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
